region            = "us-east-1"
ami               = "ami-02dfbd4ff395f2a1b"   
instance_type     = "t2.micro"
key_pair_name     = "key"
private_key_path  = "D:/Terraform/Terraform/practice/provisioner_practice/key"
public_key_path   = "D:/Terraform/Terraform/practice/provisioner_practice/key.pub"